spring.application.name=clinica-veterinaria

#Ponemos por defecto el perfil de test
spring.profiles.active=test

# muestra el mensaje y los errores de binding en las respuestas 4xx/5xx
server.error.include-message=always
server.error.include-binding-errors=always