#----COMENTAMOS LAS CONFIGURACIONES ANTERIORES ORIGINALES----
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER_NAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.application.name=app_vet
s#pring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#server.port=8080
#spring.jpa.database-platform=${DB_PLATFORM}

# Hacemos las configuraciones de H2
# === Datasource H2 en memoria solo para tests ===
spring.datasource.url=jdbc:h2:mem:vetdb;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=vetuser
spring.datasource.password=

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

# Logging de pruebas más limpio
logging.level.org.springframework.test=INFO
