# Configuraciones Basicas
spring.application.name=springSecurityBasic

# Configuraciones de Seguridad
spring.security.user.name=${SS_USER}
spring.security.user.password=${SS_PASSWORD}

# Configuraciones de BD
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USER}
spring.datasource.password=${BD_PASSWORD}

#Config de JWT
security.jwt.private.key=${PRIVATE_KEY}
#Acá puedo "inventar" el "nombre de usuario" que quiera
security.jwt.user.generator=${USER_GENERATOR}
